# Generated by Django 5.0.3 on 2025-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdiocese',
            name='DIO_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='tbdiocese',
            name='DIO_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
