# Generated by Django 5.0.3 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0002_add_dio_numero_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdiocese',
            name='DIO_complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
