# Generated by Django 5.0.3 on 2025-11-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0004_tbdizimistas_dis_dia_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBGERDIZIMO',
            fields=[
                ('GER_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('GER_mesano', models.DateField(help_text='Mês e ano de referência do dízimo', verbose_name='Mês/Ano')),
                ('GER_dtvencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('GER_vlr_dizimo', models.DecimalField(decimal_places=2, help_text='Valor esperado do dízimo', max_digits=10, verbose_name='Valor do Dízimo')),
                ('GER_dtpagto', models.DateField(blank=True, help_text='Data em que o pagamento foi realizado', null=True, verbose_name='Data de Pagamento')),
                ('GER_vlr_pago', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente pago', max_digits=10, null=True, verbose_name='Valor Pago')),
                ('GER_data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('GER_data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('GER_dizimista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerenciamentos_dizimo', to='app_igreja.tbdizimistas', verbose_name='Dizimista')),
            ],
            options={
                'verbose_name': 'Gerenciamento de Dízimo',
                'verbose_name_plural': 'Gerenciamentos de Dízimos',
                'db_table': 'TBGERDIZIMO',
                'ordering': ['-GER_mesano', 'GER_dizimista__DIS_nome'],
                'indexes': [models.Index(fields=['GER_mesano', 'GER_dizimista'], name='TBGERDIZIMO_GER_mes_650d9a_idx'), models.Index(fields=['GER_dtvencimento'], name='TBGERDIZIMO_GER_dtv_636ebf_idx')],
            },
        ),
    ]
