# Generated by Django 5.0.3 on 2025-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0005_tbgerdizimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbgerdizimo',
            name='GER_observacao',
            field=models.CharField(blank=True, help_text='Observações sobre o pagamento', max_length=100, null=True, verbose_name='Observação'),
        ),
    ]
