# Generated by Django 5.0.3 on 2025-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0003_add_dio_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdizimistas',
            name='DIS_dia_pagamento',
            field=models.IntegerField(blank=True, help_text='Dia do mês em que o dizimista prefere fazer o pagamento (1-31)', null=True, verbose_name='Dia do Pagamento'),
        ),
    ]
