# Generated by Django 5.0.3 on 2025-12-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0006_add_ger_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbitem_escala',
            name='ITE_ESC_STATUS',
            field=models.CharField(choices=[('EM_ABERTO', 'Em aberto'), ('RESERVADO', 'Reservado'), ('DEFINIDO', 'Definido')], default='EM_ABERTO', help_text='Status do item da escala', max_length=20, verbose_name='Status'),
        ),
    ]
