# Generated by Django 5.0.3 on 2025-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0007_add_reservado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbitem_escala',
            name='ITE_ESC_SITUACAO',
            field=models.BooleanField(default=False, help_text='Situação do item da escala', verbose_name='Situação'),
        ),
    ]
