# Generated by Django 5.0.3 on 2025-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0008_add_ite_esc_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbparoquia',
            name='PAR_url_facebook',
            field=models.URLField(blank=True, help_text='URL da página do Facebook da paróquia', null=True, verbose_name='URL do Facebook'),
        ),
        migrations.AddField(
            model_name='tbparoquia',
            name='PAR_url_instagram',
            field=models.URLField(blank=True, help_text='URL do perfil do Instagram da paróquia', null=True, verbose_name='URL do Instagram'),
        ),
        migrations.AddField(
            model_name='tbparoquia',
            name='PAR_url_youtube',
            field=models.URLField(blank=True, help_text='URL do canal do YouTube da paróquia', null=True, verbose_name='URL do YouTube'),
        ),
    ]
