# Generated by Django 5.0.3 on 2025-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0009_tbparoquia_par_url_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcolaboradores',
            name='COL_estado_civil',
            field=models.CharField(blank=True, choices=[('', 'Selecione...'), ('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável'), ('SEPARADO', 'Separado(a)')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
    ]
