# Generated by Django 5.0.3 on 2025-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0010_alter_tbcolaboradores_col_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcolaboradores',
            name='COL_funcao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Função'),
        ),
    ]
