# Generated by Django 5.0.3 on 2025-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0011_tbcolaboradores_col_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbitem_escala',
            name='ITE_ESC_FUNCAO',
            field=models.IntegerField(blank=True, help_text='ID da função do colaborador no momento da atribuição (preserva histórico)', null=True, verbose_name='Função'),
        ),
    ]
