# Generated by Django 5.0.3 on 2025-12-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0012_tbitem_escala_ite_esc_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbparoquia',
            name='PAR_url_youtube_video_gravado',
            field=models.URLField(blank=True, help_text='URL do vídeo gravado do YouTube para exibir quando não houver transmissão ao vivo (ex: https://www.youtube.com/watch?v=VIDEO_ID)', null=True, verbose_name='URL do Vídeo Gravado (YouTube)'),
        ),
    ]
