# Generated by Django 5.0.3 on 2025-12-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0014_remove_par_url_youtube_video_gravado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcolaboradores',
            name='COL_grupo_liturgico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grupo Litúrgico'),
        ),
    ]
