# Generated by Django 5.0.3 on 2025-12-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0015_tbcolaboradores_col_grupo_liturgico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbitem_modelo',
            options={'ordering': ['ITEM_MOD_MODELO', 'ITEM_MOD_ID'], 'verbose_name': 'Item do Modelo', 'verbose_name_plural': 'Itens do Modelo'},
        ),
        migrations.CreateModel(
            name='TBAGENDAMES',
            fields=[
                ('AGE_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE_MES', models.DateField(help_text='Data do primeiro dia do mês', verbose_name='Mês')),
                ('AGE_DIA', models.IntegerField(help_text='Dia do mês (1-31)', verbose_name='Dia')),
                ('AGE_ENCARGOS', models.TextField(blank=True, help_text='Encargos do dia', null=True, verbose_name='Encargos')),
                ('AGE_OCORRENCIAS', models.CharField(blank=True, help_text='Ocorrências do dia (separadas por vírgula)', max_length=200, null=True, verbose_name='Ocorrências')),
                ('AGE_DATA_CRIACAO', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('AGE_DATA_ATUALIZACAO', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('AGE_MODELO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='app_igreja.tbmodelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Agenda do Mês',
                'verbose_name_plural': 'Agendas do Mês',
                'db_table': 'TBAGENDAMES',
                'ordering': ['AGE_MES', 'AGE_DIA'],
                'unique_together': {('AGE_MES', 'AGE_DIA')},
            },
        ),
    ]
