# Generated by Django 5.0.3 on 2025-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0016_alter_tbitem_modelo_options_tbagendames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_OCORRENCIAS',
        ),
        migrations.AlterField(
            model_name='tbagendames',
            name='AGE_MODELO',
            field=models.IntegerField(blank=True, help_text='ID do modelo selecionado', null=True, verbose_name='Modelo'),
        ),
    ]
