# Generated by Django 5.0.3 on 2025-12-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0017_remove_tbagendames_age_ocorrencias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbagendames',
            options={'ordering': ['-AGE_MES'], 'verbose_name': 'Agenda do Mês', 'verbose_name_plural': 'Agendas do Mês'},
        ),
        migrations.AlterUniqueTogether(
            name='tbagendames',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tbagendames',
            name='AGE_MES',
            field=models.DateField(help_text='Data do primeiro dia do mês', unique=True, verbose_name='Mês'),
        ),
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_DATA_ATUALIZACAO',
        ),
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_DATA_CRIACAO',
        ),
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_DIA',
        ),
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_ENCARGOS',
        ),
        migrations.RemoveField(
            model_name='tbagendames',
            name='AGE_MODELO',
        ),
        migrations.CreateModel(
            name='TBITEAGENDAMES',
            fields=[
                ('AGE_ITE_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE_ITE_DIA', models.IntegerField(help_text='Dia do mês (1-31)', verbose_name='Dia')),
                ('AGE_ITE_MODELO', models.IntegerField(blank=True, help_text='ID do modelo selecionado', null=True, verbose_name='Modelo')),
                ('AGE_ITE_ENCARGOS', models.TextField(blank=True, help_text='Encargos do dia', null=True, verbose_name='Encargos')),
                ('AGE_ITE_DATA_CRIACAO', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('AGE_ITE_DATA_ATUALIZACAO', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('AGE_ITE_MES', models.ForeignKey(db_column='AGE_ITE_MES', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_igreja.tbagendames', verbose_name='Agenda do Mês')),
            ],
            options={
                'verbose_name': 'Item da Agenda do Mês',
                'verbose_name_plural': 'Itens da Agenda do Mês',
                'db_table': 'TBITEAGENDAMES',
                'ordering': ['AGE_ITE_MES', 'AGE_ITE_DIA'],
                'unique_together': {('AGE_ITE_MES', 'AGE_ITE_DIA')},
            },
        ),
    ]
