# Generated by Django 5.0.3 on 2025-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0018_alter_tbagendames_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbiteagendames',
            name='AGE_ITE_HORARIO',
            field=models.TimeField(blank=True, help_text='Horário do dia', null=True, verbose_name='Horário'),
        ),
    ]
