# Generated by Django 5.0.3 on 2025-12-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0019_tbiteagendames_age_ite_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbitem_escala',
            name='ITE_ESC_JANELA',
            field=models.IntegerField(blank=True, help_text='Tipo de janela de leitura (1=Todas Leituras, 2=Diferente da escolha Anterior, 3=Diferente das últimas duas escolhidas)', null=True, verbose_name='Janela'),
        ),
    ]
