# Generated by Django 5.0.3 on 2026-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0020_tbitem_escala_ite_esc_janela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbliturgia',
            name='LIT_DATALIT',
            field=models.DateField(db_index=True, verbose_name='Data da Liturgia'),
        ),
    ]
