# Generated by Django 5.0.3 on 2026-01-30 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0021_alter_tbliturgia_lit_datalit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_data_celebracao',
            field=models.DateField(verbose_name='Data da Celebração'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_local',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_nome_solicitante',
            field=models.CharField(max_length=200, verbose_name='Nome do Solicitante'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_participantes',
            field=models.PositiveIntegerField(verbose_name='Número de Participantes'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_telefone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tbcelebracoes',
            name='CEL_tipo_celebracao',
            field=models.CharField(choices=[('batismo', 'Batismo'), ('casamento', 'Casamento'), ('primeira_comunhao', '1ª Comunhão'), ('crisma', 'Crisma'), ('missa_setimo_dia', 'Missa 7º Dia'), ('bodas', 'Bodas'), ('outras', 'Outras')], max_length=50, verbose_name='Tipo de Celebração'),
        ),
        migrations.AlterField(
            model_name='tbparoquia',
            name='PAR_horarios_fixos_json',
            field=models.TextField(blank=True, default='{}', help_text='Horários fixos por dia da semana em formato JSON', null=True, verbose_name='Horários Fixos de Celebração'),
        ),
    ]
