# Generated by Django 5.0.3 on 2026-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0022_alter_tbcelebracoes_cel_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbagendames',
            name='AGE_MES',
            field=models.DateField(help_text='Primeiro dia do mês', unique=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='tbiteagendames',
            name='AGE_ITE_ENCARGOS',
            field=models.TextField(blank=True, null=True, verbose_name='Encargos'),
        ),
        migrations.AlterField(
            model_name='tbiteagendames',
            name='AGE_ITE_HORARIO',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='tbiteagendames',
            name='AGE_ITE_MODELO',
            field=models.IntegerField(blank=True, help_text='ID do modelo', null=True, verbose_name='Modelo'),
        ),
    ]
