# Generated by Django 5.0.3 on 2026-02-02 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_igreja', '0023_alter_tbagendames_age_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbanners',
            name='BAN_LINK',
            field=models.CharField(blank=True, help_text='URL do site do patrocinador', max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='tbgerdizimo',
            name='GER_dtpagto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='tbgerdizimo',
            name='GER_mesano',
            field=models.DateField(help_text='Mês e ano de referência', verbose_name='Mês/Ano'),
        ),
        migrations.AlterField(
            model_name='tbgerdizimo',
            name='GER_observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='tbgerdizimo',
            name='GER_vlr_dizimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Dízimo'),
        ),
        migrations.AlterField(
            model_name='tbgerdizimo',
            name='GER_vlr_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_data_mural',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Mural'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_foto1_mural',
            field=models.ImageField(blank=True, null=True, upload_to='mural/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_foto2_mural',
            field=models.ImageField(blank=True, null=True, upload_to='mural/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_foto3_mural',
            field=models.ImageField(blank=True, null=True, upload_to='mural/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_foto4_mural',
            field=models.ImageField(blank=True, null=True, upload_to='mural/', verbose_name='Foto 4'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_foto5_mural',
            field=models.ImageField(blank=True, null=True, upload_to='mural/', verbose_name='Foto 5'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_legenda1_mural',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Foto 1'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_legenda2_mural',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Foto 2'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_legenda3_mural',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Foto 3'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_legenda4_mural',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Foto 4'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_legenda5_mural',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Foto 5'),
        ),
        migrations.AlterField(
            model_name='tbmural',
            name='MUR_titulo_mural',
            field=models.CharField(max_length=255, verbose_name='Título do Mural'),
        ),
        migrations.DeleteModel(
            name='TBDOACAODIZIMO',
        ),
    ]
